services:
  - type: web
    name: list-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://list-xckn.onrender.com/api
