services:
  - type: web
    name: list-backend
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_AVAILABLE
        value: "false"
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_URL
        value: https://list-xckn.onrender.com
      - key: MINI_APP_URL
        value: https://stellular-haupia-9bddae.netlify.app/
      - key: FRONTEND_URL
        value: https://stellular-haupia-9bddae.netlify.app/
